### ISSUE TITLE
There is something wrong with the newest oh-my-zsh

### ISSUE THREAD

**Issue by weakiwi** [tony/tmux-config#30]
![](http://yotuku.cn/link?url=41hzgx6lf&tk_plan=free&tk_storage=tietuku&tk_vuid=73a7fe2c-c3f5-4cca-9ec0-05b0674b3388&tk_time=2016111013)

**Comment by tony** [comment]
Have you tried a fresh tmux session? ``stty sane``, ``reset``?

**Comment by weakiwi** [comment]
I have tried `stty sane` and `reset`, it didn't work.

**Comment by tony** [comment]
Can you try a totally fresh terminal and totally new tmux session?


On November 10, 2016 at 10:44:48 PM, weakiwi (notifications@github.com)
wrote:

I have tried stty sane and reset, it didn't work.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tony/tmux-config/issues/30#issuecomment-259880246>, or mute
the thread
