### ISSUE TITLE
How can I remove tmux-conf? I'd like to turn back pure tmux

### ISSUE THREAD

**Issue by davidmgkang** [tony/tmux-config#40]
How can I remove tmux-conf? I'd like to turn back to **pure tmux**.
Could you tell me what should I do?

**Comment by davidmgkang** [comment]
I'm  using tmux 1.6 on CentOS 6.7

**Comment by tony** [comment]
Remove the ``~/.tmux.conf`` file.

``rm ~/.tmux.conf``

**Comment by tony** [comment]
Also it would be helpful to read up on tmux configurations. One sec:

https://leanpub.com/the-tao-of-tmux/read#config

So I think that section of *The Tao of tmux* should help.

I'm going to close this issue since it's general tmux support. But I think that link will be helpful, because it explains how tmux configurations are loaded.
